### ISSUE TITLE
Todo/ bugs

### ISSUE THREAD

**Issue by okg00dbye** [AY2021S1-CS2103-T14-2/tp#155]
fixed?
- [x] attempt with 0 questions will cause array index out of bounds exception when starting the app again
- [x] wrong colour label in true false
- [x] add help to performance gui and change performance gui icon
- [x] fix my png
- [x] finding with spaces
- [ ] specify in ug that find is not accumulative
- [ ] more specific user feedback for sort
- [ ] specify prefixes are case sensitive in ug
- [ ] flip after finding brings back original list
- [x] single word commands can have extra parameters 
- [ ] (if got time) more specific user feedback for commands that work in other sections
